name: Labeling

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled, unlabeled]
  workflow_call:
    secrets:
      github-token:
        description: 'The Github token'
        required: false

jobs:
  labels-test:
    name: Assign and test labels from conventional-commits
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Assign labels
        id: action-assign-labels
        uses: mauroalderete/action-assign-labels@v1
        with:
          github-token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}
          conventional-commits: |
            conventional-commits:
              - type: 'fix'
                nouns: ['FIX', 'Fix', 'fix', 'FIXED', 'Fixed', 'fixed']
                labels: ['bug', 'versioning/patch']
              - type: 'feature'
                nouns: ['FEATURE', 'Feature', 'feature', 'FEAT', 'Feat', 'feat']
                labels: ['enhancement', 'versioning/minor']
              - type: 'breaking_change'
                nouns: ['BREAKING CHANGE', 'BREAKING', 'BREAK', 'breaking change', 'breaking', 'break', 'MAJOR']
                labels: ['BREAKING CHANGE', 'versioning/major']
              - type: 'refactor'
                nouns: ['Refactor', 'Refact', 'Refac', 'refac', 'refact', 'refactor', 'REFAC', 'REFACT', 'REFACTOR', 'refacs', 'refacts', 'refactors', 'REFACS', 'REFACTS', 'REFACTORS']
                labels: ['refactor', 'versioning/patch']
              - type: 'dependencies'
                nouns: ['dependencies', 'dependencie', 'depends', 'depend', 'deps', 'dep', 'chore']
                labels: ['dependencies', 'versioning/patch']
              - type: 'build'
                nouns: ['build', 'rebuild']
                labels: ['build', 'versioning/patch']
              - type: 'builddeps'
                nouns: ['build(deps)', 'build(deps-dev)']
                labels: ['build', 'dependencies', 'versioning/patch']
              - type: 'documentation'
                nouns: ['doc', 'docs', 'docu', 'document', 'documentation']
                labels: ['documentation', 'versioning/patch']
              - type: 'config'
                nouns: ['config', 'conf', 'configs', 'confs', 'cofiguration', 'cofigurations', 'configure']
                labels: ['config', 'versioning/patch']
              - type: 'ci'
                nouns: ['ci', 'CI']
                labels: ['ci', 'versioning/patch']
              - type: 'test'
                nouns: ['test', 'tests', 'testing']
                labels: ['test']
              - type: 'wip'
                nouns: ['wip', 'WIP', 'Wip']
                labels: ['wip']

      - name: Verify labels
        id: action-verify-labels
        uses: mauroalderete/action-verify-labels@v1
        with:
          none: question, wontfix, invalid, duplicate
          some: versioning/patch, versioning/minor, versioning/major
          request-review: true
          request-review-header: "**:bookmark: verify-labels-action**"
          github-token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}
